USE [master]
GO
/****** Object:  Database [CasoEstudioLN]    Script Date: 17/8/2023 09:17:50 PM ******/
CREATE DATABASE [CasoEstudioLN]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CasoEstudioLN', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CasoEstudioLN.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CasoEstudioLN_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CasoEstudioLN_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [CasoEstudioLN] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CasoEstudioLN].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CasoEstudioLN] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CasoEstudioLN] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CasoEstudioLN] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CasoEstudioLN] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CasoEstudioLN] SET ARITHABORT OFF 
GO
ALTER DATABASE [CasoEstudioLN] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [CasoEstudioLN] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CasoEstudioLN] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CasoEstudioLN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CasoEstudioLN] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CasoEstudioLN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CasoEstudioLN] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CasoEstudioLN] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CasoEstudioLN] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CasoEstudioLN] SET  ENABLE_BROKER 
GO
ALTER DATABASE [CasoEstudioLN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CasoEstudioLN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CasoEstudioLN] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CasoEstudioLN] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CasoEstudioLN] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CasoEstudioLN] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CasoEstudioLN] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CasoEstudioLN] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CasoEstudioLN] SET  MULTI_USER 
GO
ALTER DATABASE [CasoEstudioLN] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CasoEstudioLN] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CasoEstudioLN] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CasoEstudioLN] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CasoEstudioLN] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CasoEstudioLN] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [CasoEstudioLN] SET QUERY_STORE = ON
GO
ALTER DATABASE [CasoEstudioLN] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [CasoEstudioLN]
GO
/****** Object:  Table [dbo].[CasasSistema]    Script Date: 17/8/2023 09:17:50 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CasasSistema](
	[IdCasa] [bigint] IDENTITY(1,1) NOT NULL,
	[DescripcionCasa] [varchar](30) NOT NULL,
	[PrecioCasa] [decimal](10, 2) NOT NULL,
	[UsuarioAlquiler] [varchar](30) NULL,
	[FechaAlquiler] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdCasa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[CasasSistema] ON 
GO
INSERT [dbo].[CasasSistema] ([IdCasa], [DescripcionCasa], [PrecioCasa], [UsuarioAlquiler], [FechaAlquiler]) VALUES (1, N'Casa en San Jose', CAST(190000.00 AS Decimal(10, 2)), NULL, NULL)
GO
INSERT [dbo].[CasasSistema] ([IdCasa], [DescripcionCasa], [PrecioCasa], [UsuarioAlquiler], [FechaAlquiler]) VALUES (2, N'Casa en Alajuela', CAST(145000.00 AS Decimal(10, 2)), NULL, NULL)
GO
INSERT [dbo].[CasasSistema] ([IdCasa], [DescripcionCasa], [PrecioCasa], [UsuarioAlquiler], [FechaAlquiler]) VALUES (3, N'Casa en Cartago', CAST(115000.00 AS Decimal(10, 2)), NULL, NULL)
GO
INSERT [dbo].[CasasSistema] ([IdCasa], [DescripcionCasa], [PrecioCasa], [UsuarioAlquiler], [FechaAlquiler]) VALUES (4, N'Casa en Heredia', CAST(122000.00 AS Decimal(10, 2)), NULL, NULL)
GO
INSERT [dbo].[CasasSistema] ([IdCasa], [DescripcionCasa], [PrecioCasa], [UsuarioAlquiler], [FechaAlquiler]) VALUES (5, N'Casa en Guanacaste', CAST(105000.00 AS Decimal(10, 2)), NULL, NULL)
GO
SET IDENTITY_INSERT [dbo].[CasasSistema] OFF
GO
USE [master]
GO
ALTER DATABASE [CasoEstudioLN] SET  READ_WRITE 
GO
